bootkube.sh: pivot bootstrap node for OKD installs
OKD is using plain FCOS, which doesn't have MCD binary to pivot.
It should extract it from machine-config-daemon image and run pivot manually.
This also extract necessary files and manifests from machine-os-content image

diff --git a/data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template b/data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
--- a/data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
+++ b/data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
@@ -17,3 +17,20 @@ do
     echo "Pull failed. Retrying $RELEASE_IMAGE..."
 done
 
+{{if .IsOKD -}}
+# Pivot bootstrap to FCOS + OKD machine-os-content
+if [ ! -f /opt/openshift/.pivot-done ]; then
+  . /usr/local/bin/release-image.sh
+
+  # Run pre-pivot.sh script to update bootstrap node
+  MACHINE_CONFIG_OSCONTENT=$(image_for machine-os-content)
+  while ! podman pull --quiet "$MACHINE_CONFIG_OSCONTENT"
+  do
+      echo "Pull failed. Retrying $MACHINE_CONFIG_OSCONTENT..."
+  done
+  mnt=$(podman image mount "${MACHINE_CONFIG_OSCONTENT}")
+  pushd ${mnt}/bootstrap
+    . ./pre-pivot.sh
+  popd
+fi
+{{end -}}
